/-
# CountingLemmas.lean — the counting half of the elementary core

`GapCertificate.lean` proves the INJECTIVITY halves of the two uniform-fibre lemmas
(`fact1_injective`, `sb_injective`). This file proves the CARDINALITY halves: the
uniform fibre count for CU, the shell cardinality `|S_j| = 2^(k-1-j)` (via SB
surjectivity), and the consistency identity that the shells plus the single defect
residue `r*` exhaust the odd residues mod `2^k`.

Everything here is finite 2-group arithmetic in `ℕ` with explicit `%`, matching
`GapCertificate.lean`'s deliberate choice of `Nat`/`Int` windows over `ZMod`.

--------------------------------------------------------------------------------
## Section 0. TARGET STATEMENTS, QUOTED FROM THE SOURCE DOCUMENTS
--------------------------------------------------------------------------------

Source A: `HALFSHIFT_S4_LEMMA_A_PROOF.md`, Section 1.

> **Lemma CU.** Fix `K >= 1` and an odd `x` with `v := v2(3x+1) < K`. Put
> `q0 := (3x+1)/2^v` (odd). As `m` ranges over `Z/2^K`, the residue
> `Syr(x + m*2^K) mod 2^K` is **uniform over the coset**
> `C := q0 + 2^{K-v} * (Z/2^K)`, a set of `2^v` residues, each attained exactly
> `2^{K-v}` times.

and its step (b):

> Its image is the subgroup generated by `gcd(c, 2^K) = 2^{K-v}`, namely
> `2^{K-v}*(Z/2^K)`, of order `2^K / 2^{K-v} = 2^v`; its kernel `{m : 2^v | m}`
> has order `2^{K-v}`, so every image element has exactly `2^{K-v}` preimages.

  ORIENTATION (calibrated, see Section 6): image size `2^v`, fibre size `2^{K-v}`.
  The document is right. NOTE: the task plan's gloss "each Syracuse image value is
  hit by exactly 2^v lift indices m" is the INVERTED reading and is FALSE for
  `v ≠ K-v`; the enumeration in Section 6 settles it against the document.

> **Lemma SB.** Fix `1 <= j <= k-2`. The map `psi(r) := (3r+1)/2^j mod 2^{k-j}`
> is a **bijection** from the shell
> `S_j := { r : 0 < r < 2^k, r odd, v2(3r+1) = j }` onto the odd residues
> mod `2^{k-j}`.
>
> Surjective by counting: the shell `S_j` has `|S_j| = 2^{k-1-j}` elements (the
> odd `r` with `v2(3r+1) = j`; the AP `3r+1` is equidistributed mod `2^{j+1}`
> since 3 is a unit), and the target (odd residues mod `2^{k-j}`) also has
> `2^{k-1-j}` elements; an injection between equal finite sets is a bijection.

  m-RANGE CONVENTION, PINNED: `r` ranges over the half-open window `[0, 2^k)`
  (`Finset.range (2^k)`), and the lift index `m` of CU over `[0, 2^K)`. Both
  `GapCertificate.lean`'s `fact1_injective` and `sb_injective` already use exactly
  this window (`0 ≤ m`, `m < 2^k`), so no re-basing is needed.

  j-RANGE, PINNED AND WIDENED HONESTLY: Lemma SB is *stated* for `1 ≤ j ≤ k-2`
  because that is the range the upper cascade consumes (`b ≤ k-2`). The counting
  statement `|S_j| = 2^{k-1-j}` and the bijection both hold on the strictly larger
  range `1 ≤ j ≤ k-1` (at `j = k-1` both sides have one element). We prove the
  larger range, because the consistency identity in Section 5 needs the shell
  `j = k-1` to exist — silently shrinking the range to `k-2` would leave
  `2^{k-1} - 2` unaccounted for instead of `2^{k-1} - 1`. This is a widening of
  the source claim, never a narrowing.

Source B: `STEP4_BLOCK_FORMULA_FOUNDATION.md` (R1–R3) and
`HALFSHIFT_S4_LEMMA_A_PROOF.md` Section 2:

> Exactly ONE residue fails it: `r* = (4^{ceil(k/2)}-1)/3`, the unique odd `r`
> with `v2(3r+1) >= k` (the same `r*` as the rank-1 S_odd theorem).

> `r*` is the unique residue with `v2(3r*+1) >= k` (a unique `-3^{-1}` solution),
> so exactly one column is nonzero.

  r* CONVENTION, PINNED: `r*` is characterised here by the *inequality*
  `k ≤ v2(3r+1)` (equivalently `2^k ∣ 3r+1`), NOT by `v2(3r+1) = k`. That matters:
  for `k = 3`, `r* = 5` and `v2(16) = 4 > k`. The defect set is
  `defectSet k`, and `defect_card` proves it is a singleton. It is handled as an
  explicit extra term in the partition (Section 5), never by shrinking the j-range.

--------------------------------------------------------------------------------
## SIGN SCOPE (3x+1 vs 3x-1)
--------------------------------------------------------------------------------

The METHOD here is sign-agnostic: every proof uses only that `3` is a unit in
`ℤ/2^N` (i.e. `3` is odd) plus the image/kernel count of multiplication by a
2-power on a cyclic 2-group. Nothing uses the sign of the `+1`.

The CONSTANTS are `3x+1`-specific in exactly one place: the identity of the defect
residue. Here `r*` solves `3r ≡ -1`, i.e. `r* = -3^{-1} mod 2^k`. For the `3x-1`
control the same argument runs verbatim with `3r-1` in place of `3r+1`, and the
defect residue is `r* = +3^{-1} mod 2^k`. The shell cardinalities `|S_j| =
2^{k-1-j}`, the CU fibre count `2^{K-v}`, and the consistency identity
`Σ_j |S_j| = 2^{k-1} - 1` are IDENTICAL for both models. Per
`CYCLE_CLAIM_REFUTED.md`, this is exactly why nothing in this file (or downstream
of it) has cycle content: `3x-1` has real cycles and satisfies these counts too.

--------------------------------------------------------------------------------
## ABSURD-HEIGHT CHECK (no constant drifts with k)
--------------------------------------------------------------------------------

Every theorem below is stated for all `k`, `K`, `j`, `v` with no numeric side
conditions beyond the range bounds. Instantiating at `k = 10^9, j = 30`:
`|S_30| = 2^(10^9 - 31)` and `Σ_{j=1}^{10^9-1} |S_j| = 2^(10^9 - 1) - 1`, still
exactly one defect residue. At `K = 10^9, v = 30`: image size `2^30`, fibre size
`2^(10^9 - 30)`. No constant in any statement depends on the height.
-/
import GapCertificate

namespace CountingLemmas

open Finset
open GapCertificate

/-!
--------------------------------------------------------------------------------
## Section 1. Two counting primitives on `ℤ/2^k`
--------------------------------------------------------------------------------

(1) A residue class mod `2^m` meets `[0, 2^k)` in exactly `2^(k-m)` points.
(2) `r ↦ 3r + a` is a bijection of `[0, 2^m)` onto the residues mod `2^m`
    (the "3 is a unit" input, obtained from `GapCertificate.eq_of_two_pow_dvd_three_mul_sub`
    plus a pigeonhole, so no inverse of 3 is ever constructed).
-/

/-- `0 < 2^n`, used constantly below. -/
private theorem tp (n : ℕ) : (0 : ℕ) < 2 ^ n := Nat.two_pow_pos n

/-- **Counting primitive 1.** For `m ≤ k` and `c < 2^m`, the residue class
`{ r ∈ [0, 2^k) : r ≡ c (mod 2^m) }` has exactly `2^(k-m)` elements. -/
theorem residue_class_card {m k c : ℕ} (hmk : m ≤ k) (hc : c < 2 ^ m) :
    ((range (2 ^ k)).filter (fun r => r % 2 ^ m = c)).card = 2 ^ (k - m) := by
  have hsplit : (2 : ℕ) ^ m * 2 ^ (k - m) = 2 ^ k := by
    rw [← pow_add]; congr 1; omega
  have hpos : (0 : ℕ) < 2 ^ m := tp m
  have hinj : Function.Injective (fun t => c + 2 ^ m * t) := by
    intro a b h
    simp only at h
    exact Nat.eq_of_mul_eq_mul_left hpos (by omega)
  have hset : (range (2 ^ k)).filter (fun r => r % 2 ^ m = c)
      = (range (2 ^ (k - m))).image (fun t => c + 2 ^ m * t) := by
    ext r
    simp only [mem_filter, mem_range, mem_image]
    constructor
    · rintro ⟨hr, hmod⟩
      refine ⟨r / 2 ^ m, ?_, ?_⟩
      · exact Nat.div_lt_of_lt_mul (by omega)
      · have := Nat.div_add_mod r (2 ^ m)
        omega
    · rintro ⟨t, ht, rfl⟩
      constructor
      · have hle : 2 ^ m * t + 2 ^ m ≤ 2 ^ m * 2 ^ (k - m) := by
          calc 2 ^ m * t + 2 ^ m = 2 ^ m * (t + 1) := by ring
            _ ≤ 2 ^ m * 2 ^ (k - m) := Nat.mul_le_mul_left _ ht
        omega
      · rw [Nat.add_mul_mod_self_left, Nat.mod_eq_of_lt hc]
  rw [hset, card_image_of_injective _ hinj, card_range]

/-- Multiplication by `3` cannot change a `2`-power divisibility. -/
theorem two_pow_dvd_three_mul_iff (N : ℕ) (d : ℤ) :
    (2 : ℤ) ^ N ∣ 3 * d ↔ (2 : ℤ) ^ N ∣ d := by
  constructor
  · intro h
    have hcop : IsCoprime ((2 : ℤ) ^ N) 3 := by
      apply IsCoprime.pow_left
      rw [Int.isCoprime_iff_gcd_eq_one]
      norm_num
    exact hcop.dvd_of_dvd_mul_left h
  · exact fun h => h.mul_left 3

/-- **Counting primitive 2 (injectivity).** `r ↦ (3r + a) mod 2^M` is injective on
`[0, 2^M)`. This is `GapCertificate.eq_of_two_pow_dvd_three_mul_sub` in `ℕ` clothes. -/
theorem three_mul_add_inj {M a r r' : ℕ} (hr : r < 2 ^ M) (hr' : r' < 2 ^ M)
    (h : (3 * r + a) % 2 ^ M = (3 * r' + a) % 2 ^ M) : r = r' := by
  have hmod : Nat.ModEq (2 ^ M) (3 * r + a) (3 * r' + a) := h
  have hdvd0 : ((2 : ℕ) ^ M : ℤ) ∣ ((3 * r' + a : ℕ) : ℤ) - ((3 * r + a : ℕ) : ℤ) :=
    (Nat.modEq_iff_dvd).1 hmod
  push_cast at hdvd0
  have hdvd : (2 : ℤ) ^ M ∣ 3 * ((r' : ℤ) - (r : ℤ)) := by
    obtain ⟨s, hs⟩ := hdvd0
    exact ⟨s, by linarith⟩
  have habs : |(r' : ℤ) - (r : ℤ)| < 2 ^ M := by
    have h1 : (r : ℤ) < 2 ^ M := by exact_mod_cast hr
    have h2 : (r' : ℤ) < 2 ^ M := by exact_mod_cast hr'
    have h3 : (0 : ℤ) ≤ (r : ℤ) := Int.natCast_nonneg r
    have h4 : (0 : ℤ) ≤ (r' : ℤ) := Int.natCast_nonneg r'
    rw [abs_lt]; constructor <;> linarith
  have := eq_of_two_pow_dvd_three_mul_sub (N := M) hdvd habs
  exact_mod_cast this.symm

/-- **Counting primitive 2 (surjectivity).** Every residue `c < 2^M` is `3r + a`
for some `r < 2^M`. Proved by pigeonhole from injectivity: no inverse of `3` is
constructed anywhere in this file. -/
theorem three_mul_add_surj (M a : ℕ) {c : ℕ} (hc : c < 2 ^ M) :
    ∃ r, r < 2 ^ M ∧ (3 * r + a) % 2 ^ M = c := by
  have hinj : Set.InjOn (fun r => (3 * r + a) % 2 ^ M) (↑(range (2 ^ M)) : Set ℕ) := by
    intro x hx y hy hxy
    simp only [coe_range, Set.mem_Iio] at hx hy
    exact three_mul_add_inj hx hy hxy
  have himg : (range (2 ^ M)).image (fun r => (3 * r + a) % 2 ^ M) = range (2 ^ M) := by
    apply Finset.eq_of_subset_of_card_le
    · intro y hy
      simp only [mem_image, mem_range] at hy ⊢
      obtain ⟨r, _, rfl⟩ := hy
      exact Nat.mod_lt _ (tp M)
    · rw [card_image_of_injOn hinj]
  have hmem : c ∈ (range (2 ^ M)).image (fun r => (3 * r + a) % 2 ^ M) := by
    rw [himg]; simpa using hc
  simp only [mem_image, mem_range] at hmem
  obtain ⟨r, hr, hrc⟩ := hmem
  exact ⟨r, hr, hrc⟩

/-- The unique-solution form of the two primitives above. -/
theorem three_mul_add_existsUnique (M a : ℕ) {c : ℕ} (hc : c < 2 ^ M) :
    ∃! r, r < 2 ^ M ∧ (3 * r + a) % 2 ^ M = c := by
  obtain ⟨r, hr, hrc⟩ := three_mul_add_surj M a hc
  refine ⟨r, ⟨hr, hrc⟩, ?_⟩
  rintro y ⟨hy, hyc⟩
  exact three_mul_add_inj hy hr (by rw [hyc, hrc])

/-- Reduction of the affine map through `%`. -/
theorem three_mul_add_mod_mod (M a r : ℕ) :
    (3 * (r % 2 ^ M) + a) % 2 ^ M = (3 * r + a) % 2 ^ M :=
  (((Nat.mod_modEq r (2 ^ M)).mul_left 3).add_right a)

/-!
--------------------------------------------------------------------------------
## Section 2. The 2-adic valuation as a residue condition
--------------------------------------------------------------------------------
-/

/-- `v2 n = j` iff `2^j ∣ n` and `2^(j+1) ∤ n`. -/
theorem v2_eq_iff_dvd {n j : ℕ} (hn : n ≠ 0) :
    v2 n = j ↔ (2 ^ j ∣ n ∧ ¬ (2 ^ (j + 1) ∣ n)) := by
  unfold v2
  constructor
  · rintro rfl
    exact ⟨pow_padicValNat_dvd, pow_succ_padicValNat_not_dvd hn⟩
  · rintro ⟨h1, h2⟩
    have hle : j ≤ padicValNat 2 n := (padicValNat_dvd_iff_le hn).1 h1
    have hlt : ¬ (j + 1 ≤ padicValNat 2 n) := fun h => h2 ((padicValNat_dvd_iff_le hn).2 h)
    omega

/-- **The shell condition as a residue condition.** For `n ≠ 0`,
`v2 n = j` iff `n ≡ 2^j (mod 2^(j+1))`. -/
theorem v2_eq_iff_mod {n j : ℕ} (hn : n ≠ 0) :
    v2 n = j ↔ n % 2 ^ (j + 1) = 2 ^ j := by
  have hdvd21 : (2 : ℕ) ^ j ∣ 2 ^ (j + 1) := pow_dvd_pow 2 (by omega)
  have hjpos : (0 : ℕ) < 2 ^ j := tp j
  have hsucc : (2 : ℕ) ^ (j + 1) = 2 * 2 ^ j := by rw [pow_succ]; ring
  rw [v2_eq_iff_dvd hn]
  constructor
  · rintro ⟨h1, h2⟩
    have hs1 : (2 : ℕ) ^ j ∣ n % 2 ^ (j + 1) := (Nat.dvd_mod_iff hdvd21).2 h1
    have hs2 : n % 2 ^ (j + 1) ≠ 0 := fun h => h2 (Nat.dvd_of_mod_eq_zero h)
    have hs3 : n % 2 ^ (j + 1) < 2 ^ (j + 1) := Nat.mod_lt _ (tp (j + 1))
    obtain ⟨t, ht⟩ := hs1
    have htlt : t < 2 := by
      by_contra hcon
      push_neg at hcon
      have : (2 : ℕ) ^ j * 2 ≤ 2 ^ j * t := Nat.mul_le_mul_left _ hcon
      omega
    interval_cases t <;> omega
  · intro h
    refine ⟨(Nat.dvd_mod_iff hdvd21).1 (by rw [h]), ?_⟩
    rintro ⟨c, rfl⟩
    rw [Nat.mul_mod_right] at h
    omega

/-!
--------------------------------------------------------------------------------
## Section 3. The CU uniform fibre count
--------------------------------------------------------------------------------

`cuMap K v m = (3 * 2^(K-v) * m) mod 2^K` is exactly the non-constant part of
`cu_syracuse_affine`. Its fibres all have size `2^(K-v)` and its image has size
`2^v`: the orientation confirmed by the enumeration in Section 6.
-/

/-- The CU multiplication map on `ℤ/2^K`. -/
def cuMap (K v m : ℕ) : ℕ := (3 * 2 ^ (K - v) * m) % 2 ^ K

/-- `cuMap` identifies exactly the residues mod `2^v`: this is the kernel computation. -/
theorem cu_fibre_iff {K v : ℕ} (hv : v ≤ K) (m m0 : ℕ) :
    cuMap K v m = cuMap K v m0 ↔ m % 2 ^ v = m0 % 2 ^ v := by
  have hsplitZ : (2 : ℤ) ^ (K - v) * 2 ^ v = 2 ^ K := by
    rw [← pow_add]; congr 1; omega
  have hne : ((2 : ℤ) ^ (K - v)) ≠ 0 := by positivity
  constructor
  · intro h
    have hmod : Nat.ModEq (2 ^ K) (3 * 2 ^ (K - v) * m) (3 * 2 ^ (K - v) * m0) := h
    have hdvd0 : ((2 : ℕ) ^ K : ℤ) ∣
        ((3 * 2 ^ (K - v) * m0 : ℕ) : ℤ) - ((3 * 2 ^ (K - v) * m : ℕ) : ℤ) :=
      (Nat.modEq_iff_dvd).1 hmod
    push_cast at hdvd0
    obtain ⟨s, hs⟩ := hdvd0
    have hstep : (2 : ℤ) ^ (K - v) * 2 ^ v ∣ 2 ^ (K - v) * (3 * ((m0 : ℤ) - (m : ℤ))) := by
      refine ⟨s, ?_⟩
      rw [hsplitZ]
      linarith [hs]
    have h2 : (2 : ℤ) ^ v ∣ 3 * ((m0 : ℤ) - (m : ℤ)) := (mul_dvd_mul_iff_left hne).1 hstep
    have h3 : (2 : ℤ) ^ v ∣ ((m0 : ℤ) - (m : ℤ)) := (two_pow_dvd_three_mul_iff v _).1 h2
    exact (Nat.modEq_iff_dvd).2 (by exact_mod_cast h3)
  · intro h
    have hmodv : Nat.ModEq (2 ^ v) m m0 := h
    have hdvd : ((2 : ℕ) ^ v : ℤ) ∣ ((m0 : ℕ) : ℤ) - ((m : ℕ) : ℤ) :=
      (Nat.modEq_iff_dvd).1 hmodv
    obtain ⟨s, hs⟩ := hdvd
    push_cast at hs
    have hbig : ((2 : ℕ) ^ K : ℤ) ∣
        ((3 * 2 ^ (K - v) * m0 : ℕ) : ℤ) - ((3 * 2 ^ (K - v) * m : ℕ) : ℤ) := by
      push_cast
      refine ⟨3 * s, ?_⟩
      have hexp : (3 : ℤ) * 2 ^ (K - v) * (m0 : ℤ) - 3 * 2 ^ (K - v) * (m : ℤ)
          = 3 * 2 ^ (K - v) * (((m0 : ℤ)) - (m : ℤ)) := by ring
      rw [hexp, hs, ← hsplitZ]
      ring
    exact (Nat.modEq_iff_dvd).2 hbig

/-- **CU, fibre count.** Every fibre of `cuMap K v` over `[0, 2^K)` has exactly
`2^(K-v)` elements. -/
theorem cu_fibre_card {K v : ℕ} (hv : v ≤ K) (m0 : ℕ) :
    ((range (2 ^ K)).filter (fun m => cuMap K v m = cuMap K v m0)).card = 2 ^ (K - v) := by
  have hrw : (range (2 ^ K)).filter (fun m => cuMap K v m = cuMap K v m0)
      = (range (2 ^ K)).filter (fun m => m % 2 ^ v = m0 % 2 ^ v) := by
    apply filter_congr
    intro m _
    exact cu_fibre_iff hv m m0
  rw [hrw]
  exact residue_class_card hv (Nat.mod_lt _ (tp v))

/-- **CU, image is the coset subgroup.** The image of `cuMap K v` is exactly the
multiples of `2^(K-v)` in `[0, 2^K)`. -/
theorem cu_image_eq {K v : ℕ} (hv : v ≤ K) :
    (range (2 ^ K)).image (cuMap K v)
      = (range (2 ^ K)).filter (fun t => t % 2 ^ (K - v) = 0) := by
  have hsplit : (2 : ℕ) ^ (K - v) * 2 ^ v = 2 ^ K := by
    rw [← pow_add]; congr 1; omega
  have hdvdK : (2 : ℕ) ^ (K - v) ∣ 2 ^ K := pow_dvd_pow 2 (by omega)
  ext t
  simp only [mem_image, mem_filter, mem_range]
  constructor
  · rintro ⟨m, hm, rfl⟩
    refine ⟨Nat.mod_lt _ (tp K), ?_⟩
    unfold cuMap
    rw [Nat.mod_mod_of_dvd _ hdvdK,
      show (3 : ℕ) * 2 ^ (K - v) * m = 2 ^ (K - v) * (3 * m) by ring, Nat.mul_mod_right]
  · rintro ⟨htK, ht0⟩
    obtain ⟨u, hu⟩ : (2 : ℕ) ^ (K - v) ∣ t := Nat.dvd_of_mod_eq_zero ht0
    have hult : u < 2 ^ v := by
      by_contra hcon
      push_neg at hcon
      have : (2 : ℕ) ^ (K - v) * 2 ^ v ≤ 2 ^ (K - v) * u := Nat.mul_le_mul_left _ hcon
      omega
    obtain ⟨m, hm, hmu⟩ := three_mul_add_surj v 0 hult
    refine ⟨m, ?_, ?_⟩
    · refine lt_of_lt_of_le hm ?_
      calc (2 : ℕ) ^ v = 1 * 2 ^ v := (one_mul _).symm
        _ ≤ 2 ^ (K - v) * 2 ^ v := Nat.mul_le_mul_right _ Nat.one_le_two_pow
        _ = 2 ^ K := hsplit
    · unfold cuMap
      rw [show (3 : ℕ) * 2 ^ (K - v) * m = 2 ^ (K - v) * (3 * m) by ring, ← hsplit,
        Nat.mul_mod_mul_left]
      simp only [Nat.add_zero] at hmu
      rw [hmu, hu]

/-- **CU, image count.** The image of `cuMap K v` has exactly `2^v` elements. -/
theorem cu_image_card {K v : ℕ} (hv : v ≤ K) :
    ((range (2 ^ K)).image (cuMap K v)).card = 2 ^ v := by
  rw [cu_image_eq hv, residue_class_card (m := K - v) (k := K) (c := 0) (by omega) (tp (K - v)),
    show K - (K - v) = v by omega]

/-- **CU for Syracuse.** For odd `x` with `v := v2(3x+1) < K`, the fibre of
`m ↦ Syr(x + m·2^K) mod 2^K` over any attained residue has exactly `2^(K-v)`
elements: this is Lemma CU's "each attained exactly `2^{K-v}` times". -/
theorem cu_syracuse_fibre_card {x K : ℕ} (hx : x % 2 = 1) (hK : v2 (3 * x + 1) < K)
    (m0 : ℕ) :
    ((range (2 ^ K)).filter
        (fun m => syracuse (x + m * 2 ^ K) % 2 ^ K = syracuse (x + m0 * 2 ^ K) % 2 ^ K)).card
      = 2 ^ (K - v2 (3 * x + 1)) := by
  set v := v2 (3 * x + 1) with hv
  set q0 := (3 * x + 1) / 2 ^ v with hq0
  have hcond : ∀ m, (syracuse (x + m * 2 ^ K) % 2 ^ K = syracuse (x + m0 * 2 ^ K) % 2 ^ K)
      ↔ cuMap K v m = cuMap K v m0 := by
    intro m
    rw [cu_syracuse_affine x m K hx hK, cu_syracuse_affine x m0 K hx hK]
    unfold cuMap
    constructor
    · intro h
      have hmod : Nat.ModEq (2 ^ K) (q0 + 3 * m * 2 ^ (K - v)) (q0 + 3 * m0 * 2 ^ (K - v)) := h
      have h2 : (3 * m * 2 ^ (K - v)) % 2 ^ K = (3 * m0 * 2 ^ (K - v)) % 2 ^ K :=
        Nat.ModEq.add_left_cancel' q0 hmod
      calc (3 * 2 ^ (K - v) * m) % 2 ^ K
          = (3 * m * 2 ^ (K - v)) % 2 ^ K := by ring_nf
        _ = (3 * m0 * 2 ^ (K - v)) % 2 ^ K := h2
        _ = (3 * 2 ^ (K - v) * m0) % 2 ^ K := by ring_nf
    · intro h
      have h2 : (3 * m * 2 ^ (K - v)) % 2 ^ K = (3 * m0 * 2 ^ (K - v)) % 2 ^ K := by
        calc (3 * m * 2 ^ (K - v)) % 2 ^ K
            = (3 * 2 ^ (K - v) * m) % 2 ^ K := by ring_nf
          _ = (3 * 2 ^ (K - v) * m0) % 2 ^ K := h
          _ = (3 * m0 * 2 ^ (K - v)) % 2 ^ K := by ring_nf
      exact Nat.ModEq.add_left q0 h2
  have hrw : (range (2 ^ K)).filter
      (fun m => syracuse (x + m * 2 ^ K) % 2 ^ K = syracuse (x + m0 * 2 ^ K) % 2 ^ K)
      = (range (2 ^ K)).filter (fun m => cuMap K v m = cuMap K v m0) := by
    apply filter_congr
    intro m _
    exact hcond m
  rw [hrw]
  exact cu_fibre_card (le_of_lt hK) m0

/-- Translation by a constant is injective on `[0, 2^K)` mod `2^K`. -/
theorem shift_injOn (q0 K : ℕ) :
    Set.InjOn (fun t => (q0 + t) % 2 ^ K) (↑(range (2 ^ K)) : Set ℕ) := by
  intro t ht t' ht' h
  simp only [coe_range, Set.mem_Iio] at ht ht'
  have hme : Nat.ModEq (2 ^ K) (q0 + t) (q0 + t') := h
  have : Nat.ModEq (2 ^ K) t t' := Nat.ModEq.add_left_cancel' q0 hme
  have h2 : t % 2 ^ K = t' % 2 ^ K := this
  rwa [Nat.mod_eq_of_lt ht, Nat.mod_eq_of_lt ht'] at h2

/-- **CU for Syracuse, image count.** For odd `x` with `v := v2(3x+1) < K`, the
residues `Syr(x + m·2^K) mod 2^K` form a set of exactly `2^v` elements — Lemma CU's
"uniform over the coset `C := q0 + 2^{K-v}·(Z/2^K)`, a set of `2^v` residues".
Together with `cu_syracuse_fibre_card` (`2^(K-v)` preimages each) this is Lemma CU
step (b) in full, and `2^v · 2^(K-v) = 2^K` closes the count. -/
theorem cu_syracuse_image_card {x K : ℕ} (hx : x % 2 = 1) (hK : v2 (3 * x + 1) < K) :
    ((range (2 ^ K)).image (fun m => syracuse (x + m * 2 ^ K) % 2 ^ K)).card
      = 2 ^ v2 (3 * x + 1) := by
  set v := v2 (3 * x + 1) with hv
  set q0 := (3 * x + 1) / 2 ^ v with hq0
  have hfun : ∀ m, syracuse (x + m * 2 ^ K) % 2 ^ K = (q0 + cuMap K v m) % 2 ^ K := by
    intro m
    rw [cu_syracuse_affine x m K hx hK]
    unfold cuMap
    have hme : Nat.ModEq (2 ^ K) (q0 + (3 * 2 ^ (K - v) * m) % 2 ^ K)
        (q0 + 3 * 2 ^ (K - v) * m) := Nat.ModEq.add_left q0 (Nat.mod_modEq _ _)
    have h1 : (q0 + (3 * 2 ^ (K - v) * m) % 2 ^ K) % 2 ^ K
        = (q0 + 3 * 2 ^ (K - v) * m) % 2 ^ K := hme
    rw [h1, show q0 + 3 * m * 2 ^ (K - v) = q0 + 3 * 2 ^ (K - v) * m by ring]
  have himg : (range (2 ^ K)).image (fun m => syracuse (x + m * 2 ^ K) % 2 ^ K)
      = ((range (2 ^ K)).image (cuMap K v)).image (fun t => (q0 + t) % 2 ^ K) := by
    rw [Finset.image_image]
    apply Finset.image_congr
    intro m _
    exact hfun m
  have hsub : ((range (2 ^ K)).image (cuMap K v) : Set ℕ) ⊆ (↑(range (2 ^ K)) : Set ℕ) := by
    intro t ht
    simp only [coe_image, Set.mem_image, coe_range, Set.mem_Iio] at ht ⊢
    obtain ⟨m, _, rfl⟩ := ht
    unfold cuMap
    exact Nat.mod_lt _ (tp K)
  rw [himg, card_image_of_injOn ((shift_injOn q0 K).mono hsub), cu_image_card (le_of_lt hK)]

/-!
--------------------------------------------------------------------------------
## Section 4. Shells, the defect residue `r*`, and `|S_j| = 2^(k-1-j)`
--------------------------------------------------------------------------------
-/

/-- The valuation shell `S_j = { r : 0 < r < 2^k, r odd, v2(3r+1) = j }`,
transcribed verbatim from Lemma SB. -/
def shell (k j : ℕ) : Finset ℕ :=
  (range (2 ^ k)).filter (fun r => 0 < r ∧ r % 2 = 1 ∧ v2 (3 * r + 1) = j)

/-- The defect set `{ r* }`: the odd `r < 2^k` with `v2(3r+1) ≥ k`. Note the
INEQUALITY: for `k = 3`, `r* = 5` has `v2(16) = 4 > k`. -/
def defectSet (k : ℕ) : Finset ℕ :=
  (range (2 ^ k)).filter (fun r => 0 < r ∧ r % 2 = 1 ∧ k ≤ v2 (3 * r + 1))

/-- The odd residues mod `2^m`: the target of SB. -/
def oddResidues (m : ℕ) : Finset ℕ := (range (2 ^ m)).filter (fun q => q % 2 = 1)

/-- For `j ≥ 1`, the side conditions `0 < r` and `r` odd in the definition of
`shell` are automatic. (Stated so the extra conditions are visibly harmless
rather than silently dropped.) -/
theorem shell_eq {k j : ℕ} (hj : 1 ≤ j) :
    shell k j = (range (2 ^ k)).filter (fun r => v2 (3 * r + 1) = j) := by
  unfold shell
  apply filter_congr
  intro r _
  constructor
  · rintro ⟨_, _, h⟩; exact h
  · intro h
    have hne : 3 * r + 1 ≠ 0 := by omega
    have hdvd : (2 : ℕ) ^ j ∣ 3 * r + 1 := ((v2_eq_iff_dvd hne).1 h).1
    have h2 : (2 : ℕ) ∣ 3 * r + 1 := dvd_trans (dvd_pow_self 2 (by omega)) hdvd
    exact ⟨by omega, by omega, h⟩

/-- The shell, as a single residue class mod `2^(j+1)`. -/
theorem shell_eq_residue_class {k j : ℕ} (hj : 1 ≤ j) (_hjk : j + 1 ≤ k) :
    ∃ c, c < 2 ^ (j + 1) ∧
      shell k j = (range (2 ^ k)).filter (fun r => r % 2 ^ (j + 1) = c) := by
  have hlt : (2 : ℕ) ^ j < 2 ^ (j + 1) := by
    have h1 : (2 : ℕ) ^ (j + 1) = 2 * 2 ^ j := by rw [pow_succ]; ring
    have h2 : (0 : ℕ) < 2 ^ j := tp j
    omega
  obtain ⟨c, hc, hcsol⟩ := three_mul_add_surj (j + 1) 1 hlt
  refine ⟨c, hc, ?_⟩
  rw [shell_eq hj]
  apply filter_congr
  intro r _
  have hne : 3 * r + 1 ≠ 0 := by omega
  rw [v2_eq_iff_mod hne]
  constructor
  · intro h
    have hstep : (3 * (r % 2 ^ (j + 1)) + 1) % 2 ^ (j + 1) = 2 ^ j := by
      rw [three_mul_add_mod_mod]; exact h
    exact three_mul_add_inj (Nat.mod_lt _ (tp (j + 1))) hc (by rw [hstep, hcsol])
  · intro h
    rw [← three_mul_add_mod_mod, h, hcsol]

/-- **SHELL CARDINALITY.** `|S_j| = 2^(k-1-j)` for every `1 ≤ j ≤ k-1`.
(Source: Lemma SB, "the shell `S_j` has `|S_j| = 2^{k-1-j}` elements".) -/
theorem shell_card {k j : ℕ} (hj : 1 ≤ j) (hjk : j + 1 ≤ k) :
    (shell k j).card = 2 ^ (k - 1 - j) := by
  obtain ⟨c, hc, hset⟩ := shell_eq_residue_class hj hjk
  rw [hset, residue_class_card (by omega) hc, show k - (j + 1) = k - 1 - j by omega]

/-- `k ≤ v2 (3r+1)` is the same as `(3r+1) ≡ 0 (mod 2^k)`. -/
theorem defect_iff {k r : ℕ} : k ≤ v2 (3 * r + 1) ↔ (3 * r + 1) % 2 ^ k = 0 := by
  have hne : 3 * r + 1 ≠ 0 := by omega
  constructor
  · intro h
    obtain ⟨c, hc⟩ := (padicValNat_dvd_iff_le hne).2 h
    rw [hc, Nat.mul_mod_right]
  · intro h
    exact (padicValNat_dvd_iff_le hne).1 (Nat.dvd_of_mod_eq_zero h)

/-- **`r*` EXISTS AND IS UNIQUE.** The defect set is a singleton for every `k ≥ 1`. -/
theorem defect_card {k : ℕ} (hk : 1 ≤ k) : (defectSet k).card = 1 := by
  obtain ⟨c, hc, hcsol⟩ := three_mul_add_surj k 1 (tp k)
  have hset : defectSet k = (range (2 ^ k)).filter (fun r => r % 2 ^ k = c) := by
    unfold defectSet
    apply filter_congr
    intro r _
    constructor
    · rintro ⟨_, _, h⟩
      have h0 : (3 * r + 1) % 2 ^ k = 0 := defect_iff.1 h
      have hstep : (3 * (r % 2 ^ k) + 1) % 2 ^ k = 0 := by
        rw [three_mul_add_mod_mod]; exact h0
      exact three_mul_add_inj (Nat.mod_lt _ (tp k)) hc (by rw [hstep, hcsol])
    · intro h
      have h0 : (3 * r + 1) % 2 ^ k = 0 := by rw [← three_mul_add_mod_mod, h, hcsol]
      have hv : k ≤ v2 (3 * r + 1) := defect_iff.2 h0
      have hne : 3 * r + 1 ≠ 0 := by omega
      have hdvd : (2 : ℕ) ∣ 3 * r + 1 :=
        dvd_trans (dvd_pow_self 2 (by omega)) ((padicValNat_dvd_iff_le hne).2 hv)
      exact ⟨by omega, by omega, hv⟩
  rw [hset, residue_class_card (le_refl k) hc, Nat.sub_self, pow_zero]

/-!
--------------------------------------------------------------------------------
## Section 5. SB surjectivity and the consistency theorem
--------------------------------------------------------------------------------
-/

/-- The SB map `ψ(r) = (3r+1)/2^j mod 2^(k-j)`. -/
def sbMap (k j r : ℕ) : ℕ := ((3 * r + 1) / 2 ^ j) % 2 ^ (k - j)

/-- `|oddResidues m| = 2^(m-1)` for `m ≥ 1`. -/
theorem oddResidues_card {m : ℕ} (hm : 1 ≤ m) : (oddResidues m).card = 2 ^ (m - 1) := by
  unfold oddResidues
  have hrw : (range (2 ^ m)).filter (fun q => q % 2 = 1)
      = (range (2 ^ m)).filter (fun q => q % 2 ^ 1 = 1) := by
    apply filter_congr; intro q _; rw [pow_one]
  rw [hrw, residue_class_card hm (by norm_num)]

/-- On a shell, the odd part `q = (3r+1)/2^j` satisfies `3r+1 = 2^j q` with `q` odd. -/
theorem shell_oddpart {k j r : ℕ} (hj : 1 ≤ j) (hr : r ∈ shell k j) :
    3 * r + 1 = 2 ^ j * ((3 * r + 1) / 2 ^ j) ∧ ((3 * r + 1) / 2 ^ j) % 2 = 1 := by
  rw [shell_eq hj, mem_filter] at hr
  have hne : 3 * r + 1 ≠ 0 := by omega
  obtain ⟨hdvd, hndvd⟩ := (v2_eq_iff_dvd hne).1 hr.2
  obtain ⟨q, hq⟩ := hdvd
  have hqv : (3 * r + 1) / 2 ^ j = q := by
    rw [hq, Nat.mul_div_cancel_left _ (tp j)]
  refine ⟨by rw [hqv]; exact hq, ?_⟩
  rw [hqv]
  rcases Nat.even_or_odd q with he | ho
  · exfalso
    obtain ⟨t, ht⟩ := he
    exact hndvd ⟨t, by rw [hq, ht, pow_succ]; ring⟩
  · exact Nat.odd_iff.1 ho

/-- **SB, injectivity on the shell** (the `ℕ` wrapper around
`GapCertificate.sb_injective`). -/
theorem sb_injOn {k j : ℕ} (hj : 1 ≤ j) (hjk : j + 1 ≤ k) :
    Set.InjOn (sbMap k j) (↑(shell k j) : Set ℕ) := by
  intro r hr r' hr' hEq
  simp only [mem_coe] at hr hr'
  obtain ⟨hq, _⟩ := shell_oddpart hj hr
  obtain ⟨hq', _⟩ := shell_oddpart hj hr'
  have hrk : r < 2 ^ k := by
    rw [shell_eq hj, mem_filter, mem_range] at hr; exact hr.1
  have hr'k : r' < 2 ^ k := by
    rw [shell_eq hj, mem_filter, mem_range] at hr'; exact hr'.1
  unfold sbMap at hEq
  have hcong : ((2 : ℤ) ^ (k - j)) ∣
      ((((3 * r + 1) / 2 ^ j : ℕ) : ℤ) - (((3 * r' + 1) / 2 ^ j : ℕ) : ℤ)) := by
    have hme : Nat.ModEq (2 ^ (k - j)) ((3 * r' + 1) / 2 ^ j) ((3 * r + 1) / 2 ^ j) := hEq.symm
    have hd := (Nat.modEq_iff_dvd).1 hme
    push_cast at hd ⊢
    exact hd
  have hmain := sb_injective (k := k) (j := j) (by omega)
    (r := (r : ℤ)) (r' := (r' : ℤ))
    (q := (((3 * r + 1) / 2 ^ j : ℕ) : ℤ)) (q' := (((3 * r' + 1) / 2 ^ j : ℕ) : ℤ))
    (Int.natCast_nonneg r) (by exact_mod_cast hrk)
    (Int.natCast_nonneg r') (by exact_mod_cast hr'k)
    (by exact_mod_cast congrArg (fun n : ℕ => (n : ℤ)) hq)
    (by exact_mod_cast congrArg (fun n : ℕ => (n : ℤ)) hq')
    hcong
  exact_mod_cast hmain

/-- **SB, surjectivity, as an image identity.** For `1 ≤ j ≤ k-1`, `ψ` maps the
shell `S_j` ONTO the odd residues mod `2^(k-j)`. -/
theorem sb_image_eq {k j : ℕ} (hj : 1 ≤ j) (hjk : j + 1 ≤ k) :
    (shell k j).image (sbMap k j) = oddResidues (k - j) := by
  have hkj : 1 ≤ k - j := by omega
  apply Finset.eq_of_subset_of_card_le
  · intro y hy
    simp only [mem_image] at hy
    obtain ⟨r, hr, rfl⟩ := hy
    obtain ⟨_, hqodd⟩ := shell_oddpart hj hr
    unfold sbMap oddResidues
    rw [mem_filter, mem_range]
    refine ⟨Nat.mod_lt _ (tp (k - j)), ?_⟩
    rw [Nat.mod_mod_of_dvd _ (dvd_pow_self 2 (by omega : k - j ≠ 0))]
    exact hqodd
  · rw [card_image_of_injOn (sb_injOn hj hjk), shell_card hj hjk, oddResidues_card hkj,
      show k - j - 1 = k - 1 - j by omega]

/-- **SB is a bijection** from the shell onto the odd residues mod `2^(k-j)`:
surjectivity + injectivity, multiplicity exactly 1. -/
theorem sb_bijective {k j : ℕ} (hj : 1 ≤ j) (hjk : j + 1 ≤ k) :
    Set.BijOn (sbMap k j) (↑(shell k j) : Set ℕ) (↑(oddResidues (k - j)) : Set ℕ) := by
  refine ⟨?_, sb_injOn hj hjk, ?_⟩
  · intro r hr
    simp only [mem_coe] at hr ⊢
    rw [← sb_image_eq hj hjk]
    exact mem_image_of_mem _ hr
  · intro y hy
    simp only [mem_coe] at hy
    rw [← sb_image_eq hj hjk] at hy
    simp only [mem_image] at hy
    obtain ⟨r, hr, hry⟩ := hy
    exact ⟨r, by simpa using hr, hry⟩

/-- Every odd `r < 2^k` lies in exactly one shell `S_j`, `1 ≤ j ≤ k-1`, or is `r*`. -/
theorem odds_partition {k : ℕ} (hk : 1 ≤ k) :
    oddResidues k = ((Icc 1 (k - 1)).biUnion (shell k)) ∪ defectSet k := by
  ext r
  constructor
  · intro hr
    simp only [oddResidues, mem_filter, mem_range] at hr
    obtain ⟨hrk, hodd⟩ := hr
    have hne : 3 * r + 1 ≠ 0 := by omega
    rw [mem_union]
    by_cases hcase : k ≤ v2 (3 * r + 1)
    · right
      simp only [defectSet, mem_filter, mem_range]
      exact ⟨hrk, by omega, hodd, hcase⟩
    · left
      push_neg at hcase
      have hj1 : 1 ≤ v2 (3 * r + 1) := by
        by_contra hcon
        push_neg at hcon
        have hz : v2 (3 * r + 1) = 0 := by omega
        have h0 := ((v2_eq_iff_dvd hne).1 hz).2
        rw [zero_add, pow_one] at h0
        exact h0 (by omega)
      rw [mem_biUnion]
      refine ⟨v2 (3 * r + 1), by rw [mem_Icc]; omega, ?_⟩
      simp only [shell, mem_filter, mem_range]
      exact ⟨hrk, by omega, hodd, trivial⟩
  · intro hr
    rw [mem_union] at hr
    simp only [oddResidues, mem_filter, mem_range]
    rcases hr with h | h
    · rw [mem_biUnion] at h
      obtain ⟨j, _, hmem⟩ := h
      simp only [shell, mem_filter, mem_range] at hmem
      exact ⟨hmem.1, hmem.2.2.1⟩
    · simp only [defectSet, mem_filter, mem_range] at h
      exact ⟨h.1, h.2.2.1⟩

/-- Geometric sum: `Σ_{j=1}^{n} 2^(n-j) = 2^n - 1`. -/
theorem geom_sum_shells (n : ℕ) : ∑ j ∈ Icc 1 n, 2 ^ (n - j) = 2 ^ n - 1 := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [show Icc 1 (n + 1) = insert (n + 1) (Icc 1 n) by
      ext x; simp only [mem_insert, mem_Icc]; omega]
    rw [Finset.sum_insert (by simp)]
    have hrw : ∑ j ∈ Icc 1 n, 2 ^ (n + 1 - j) = 2 * ∑ j ∈ Icc 1 n, 2 ^ (n - j) := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro j hj
      simp only [mem_Icc] at hj
      rw [show n + 1 - j = (n - j) + 1 by omega, pow_succ]
      ring
    rw [hrw, ih, Nat.sub_self, pow_zero, pow_succ]
    have h1 : (1 : ℕ) ≤ 2 ^ n := Nat.one_le_two_pow
    omega

/-- **THE SHELL SUM.** `Σ_{j=1}^{k-1} |S_j| = 2^(k-1) - 1`: the shells account for
every odd residue mod `2^k` except `r*`. -/
theorem shell_sum {k : ℕ} (hk : 1 ≤ k) :
    ∑ j ∈ Icc 1 (k - 1), (shell k j).card = 2 ^ (k - 1) - 1 := by
  have hrw : ∑ j ∈ Icc 1 (k - 1), (shell k j).card
      = ∑ j ∈ Icc 1 (k - 1), 2 ^ ((k - 1) - j) := by
    apply Finset.sum_congr rfl
    intro j hj
    simp only [mem_Icc] at hj
    rw [shell_card (by omega) (by omega)]
  rw [hrw, geom_sum_shells]

/-- **THE CONSISTENCY THEOREM (set level).** The shells over `1 ≤ j ≤ k-1` plus the
single defect residue `r*` partition the odd residues mod `2^k`, so their
cardinalities add up. Both sides are computed independently (the left from
`shell_card`/`defect_card`, the right from `oddResidues_card`), so this is a genuine
internal cross-check rather than a restatement. -/
theorem counting_consistency {k : ℕ} (hk : 1 ≤ k) :
    (∑ j ∈ Icc 1 (k - 1), (shell k j).card) + (defectSet k).card = (oddResidues k).card := by
  have hdisj : (↑(Icc 1 (k - 1)) : Set ℕ).PairwiseDisjoint (shell k) := by
    intro j _ j' _ hne
    simp only [Function.onFun]
    rw [Finset.disjoint_left]
    intro r hr hr'
    simp only [shell, mem_filter] at hr hr'
    exact hne (hr.2.2.2.symm.trans hr'.2.2.2)
  have hdisj2 : Disjoint ((Icc 1 (k - 1)).biUnion (shell k)) (defectSet k) := by
    rw [Finset.disjoint_left]
    intro r hr hr'
    rw [mem_biUnion] at hr
    obtain ⟨j, hj, hmem⟩ := hr
    simp only [mem_Icc] at hj
    simp only [shell, mem_filter] at hmem
    simp only [defectSet, mem_filter] at hr'
    omega
  rw [odds_partition hk, Finset.card_union_of_disjoint hdisj2, Finset.card_biUnion hdisj]

/-- **THE CONSISTENCY THEOREM (closed form).** Summing the shell cardinalities over
`1 ≤ j ≤ k-1` and adding the one defect residue `r*` gives exactly `2^(k-1)`, the
number of odd residues mod `2^k`.

Note deliberately NOT stated as `(2^(k-1) - 1) + 1 = 2^(k-1)`: that reading is true
in `ℕ` by `omega` alone for `k ≥ 1` and carries no counting content. The statement
below has `Finset.card`s on the left, so it can only be proved from
`odds_partition` + `shell_card` + `defect_card`. -/
theorem shells_plus_defect_card {k : ℕ} (hk : 1 ≤ k) :
    (∑ j ∈ Icc 1 (k - 1), (shell k j).card) + (defectSet k).card = 2 ^ (k - 1) := by
  rw [counting_consistency hk, oddResidues_card hk]

/-!
--------------------------------------------------------------------------------
## Section 6. CALIBRATION EVIDENCE (Lean `#eval` = Python enumeration = formula)
--------------------------------------------------------------------------------

`v2` is `padicValNat 2`, which is not reducible by the kernel, so the `#eval`s below
use the DECIDABLE characterisations proved above rather than `v2` itself:

  * `v2_eq_iff_mod` :  `v2 n = j  ↔  n % 2^(j+1) = 2^j`      (n ≠ 0)
  * `defect`        :  `k ≤ v2 (3r+1)  ↔  (3r+1) % 2^k = 0`  (inside `defect_card`)

Both are theorems in this file, so the `#eval`s below are evaluating exactly the
predicates the theorems are about.

### (b)/(c) shells and `r*`, k = 4 and k = 5

Lean `#eval shellCountsEval 4` = `[4, 2, 1]`, `#eval shellCountsEval 5` = `[8, 4, 2, 1]`
Formula `2^(k-1-j)`,  k=4, j=1,2,3       = `[4, 2, 1]`   (sum 7  = 2^3 - 1)
Formula `2^(k-1-j)`,  k=5, j=1,2,3,4     = `[8, 4, 2, 1]` (sum 15 = 2^4 - 1)

Python enumeration (`enum.py`, direct `v2` by trial division over all odd r < 2^k):

    k=4 odds=8  sum_shells=7  2^(k-1)-1=7  rstar=[5]  #rstar=1
        j=1:4(formula 4)OK j=2:2(formula 2)OK j=3:1(formula 1)OK
    k=5 odds=16 sum_shells=15 2^(k-1)-1=15 rstar=[21] #rstar=1
        j=1:8(formula 8)OK j=2:4(formula 4)OK j=3:2(formula 2)OK j=4:1(formula 1)OK

    (also verified k=2..8, and SB onto the odds mod 2^(k-j) with multiplicity
     exactly 1 for every j = 1..k-1)

All three agree. The `j`-range that makes the aggregate come out is `1 ≤ j ≤ k-1`,
NOT the `1 ≤ j ≤ k-2` of Lemma SB's statement; at `k-2` the sum would be
`2^(k-1) - 2`. This is why Section 0 widens the range explicitly.

### (a) CU orientation, K = 4 and K = 5

Lean `#eval cuCountsEval 4` = `[(v,image,fibre)] = [(0,1,16),(1,2,8),(2,4,4),(3,8,2)]`
Lean `#eval cuCountsEval 5` = `[(0,1,32),(1,2,16),(2,4,8),(3,8,4),(4,16,2)]`
Formula: image `2^v`, fibre `2^(K-v)`.

Python enumeration:

    K=4 v=0: image size=1  (2^v=1)  fibre sizes={16} (2^(K-v)=16)
    K=4 v=1: image size=2  (2^v=2)  fibre sizes={8}  (2^(K-v)=8)
    K=4 v=2: image size=4  (2^v=4)  fibre sizes={4}  (2^(K-v)=4)
    K=4 v=3: image size=8  (2^v=8)  fibre sizes={2}  (2^(K-v)=2)
    K=5 v=0..4: image 1,2,4,8,16 ; fibre 32,16,8,4,2 ; image = multiples of 2^(K-v): True

All three agree, and they agree with `HALFSHIFT_S4_LEMMA_A_PROOF.md` Lemma CU
("a set of `2^v` residues, each attained exactly `2^{K-v}` times"). The task plan's
inverted gloss ("hit by exactly `2^v` lift indices") is refuted at every `v ≠ K-v`,
e.g. `K=4, v=1`: 2 image points, 8 preimages each — not 2 preimages each.
-/

/-- Decidable stand-in for `v2 n = j`, justified by `v2_eq_iff_mod`. -/
def v2EqDec (n j : ℕ) : Bool := n % 2 ^ (j + 1) == 2 ^ j

/-- Shell counts, computed via the decidable characterisation. -/
def shellCountsEval (k : ℕ) : List ℕ :=
  (List.range' 1 (k - 1)).map fun j =>
    ((List.range (2 ^ k)).filter (fun r => v2EqDec (3 * r + 1) j)).length

/-- CU (image size, fibre size at `m₀ = 1`) for each `v < K`. -/
def cuCountsEval (K : ℕ) : List (ℕ × ℕ × ℕ) :=
  (List.range K).map fun v =>
    let img := ((List.range (2 ^ K)).map (cuMap K v)).eraseDups
    let fib := ((List.range (2 ^ K)).filter (fun m => cuMap K v m == cuMap K v 1)).length
    (v, img.length, fib)

-- Calibration, k = 4 and k = 5 (expected [4,2,1] and [8,4,2,1]):
#eval shellCountsEval 4
#eval shellCountsEval 5
-- Defect count (expected 1 in both cases):
#eval ((List.range (2 ^ 4)).filter (fun r => (3 * r + 1) % 2 ^ 4 == 0)).length
#eval ((List.range (2 ^ 5)).filter (fun r => (3 * r + 1) % 2 ^ 5 == 0)).length
-- CU orientation, K = 4 and K = 5:
#eval cuCountsEval 4
#eval cuCountsEval 5

/-!
--------------------------------------------------------------------------------
## Section 7. AXIOM AUDIT
--------------------------------------------------------------------------------

Every exported result is checked below. The permitted set is exactly Lean's three
classical axioms `propext`, `Classical.choice`, `Quot.sound`; nothing in this file
adds an axiom, a `sorry`, or a `True`-bodied placeholder. The check is run as
`#print axioms` on each theorem rather than by grepping for the string "axiom".
-/

#print axioms residue_class_card
#print axioms two_pow_dvd_three_mul_iff
#print axioms three_mul_add_inj
#print axioms three_mul_add_surj
#print axioms three_mul_add_existsUnique
#print axioms three_mul_add_mod_mod
#print axioms v2_eq_iff_dvd
#print axioms v2_eq_iff_mod
#print axioms cu_fibre_iff
#print axioms cu_fibre_card
#print axioms cu_image_eq
#print axioms cu_image_card
#print axioms cu_syracuse_fibre_card
#print axioms shift_injOn
#print axioms cu_syracuse_image_card
#print axioms shell_eq
#print axioms shell_eq_residue_class
#print axioms shell_card
#print axioms defect_iff
#print axioms defect_card
#print axioms oddResidues_card
#print axioms shell_oddpart
#print axioms sb_injOn
#print axioms sb_image_eq
#print axioms sb_bijective
#print axioms odds_partition
#print axioms geom_sum_shells
#print axioms shell_sum
#print axioms counting_consistency
#print axioms shells_plus_defect_card

end CountingLemmas
